name: Fetch Performance Data

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  fetch-performance:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Fetch performance data
        env:
          # Use a Personal Access Token with organization access
          # You need to create this token with 'repo' and 'read:org' scopes
          GITHUB_PAT: ${{ secrets.ORG_ACCESS_TOKEN }}
        run: |
          python - << 'EOF'
          import os
          import json
          import re
          import requests
          from github import Github
          
          # Initialize GitHub client with organization access
          # Using PAT instead of default GITHUB_TOKEN
          token = os.environ['GITHUB_PAT']  # Changed from GITHUB_TOKEN to GITHUB_PAT
          if not token:
              print("Error: ORG_ACCESS_TOKEN not set. Please add this secret to your repository.")
              exit(1)
              
          g = Github(token)
          org_name = "hsph-bst236"  # The organization name
          
          try:
              # Get the organization
              org = g.get_organization(org_name)
              print(f"Successfully accessed organization: {org_name}")
              
              # List all repositories to debug
              all_repos = list(org.get_repos())
              print(f"Total repositories in organization: {len(all_repos)}")
              
              # Get repositories in the organization with the prefix
              repos = [repo for repo in org.get_repos() if repo.name.startswith("homework-3-")]
              
              if not repos:
                  print(f"No repositories found with prefix 'homework-3-' in the {org_name} organization")
                  exit(0)
                  
              print(f"Found {len(repos)} repositories with prefix 'homework-3-' in the {org_name} organization")
              
              # Only collect runtime values
              runtime_data = []
              
              for repo in repos:
                  repo_name = repo.name
                  print(f"Processing repository: {repo_name}")
                  
                  # Check if the repository has the test workflow
                  try:
                      # First get all workflows in the repository
                      workflows = list(repo.get_workflows())
                      test_workflow = None
                      
                      # Find the test-calculate-temp-r.yml workflow
                      for workflow in workflows:
                          print(f"Found workflow: {workflow.name} ({workflow.path})")
                          if workflow.name == "Test Calculate Temp R" or workflow.path.endswith("test-calculate-temp-r.yml"):
                              test_workflow = workflow
                              break
                      
                      if not test_workflow:
                          print(f"Could not find test-calculate-temp-r.yml workflow in {repo_name}")
                          continue
                          
                      # Now get the workflow runs for this specific workflow
                      workflow_runs = list(test_workflow.get_runs())
                      latest_run = workflow_runs[0] if workflow_runs else None
                      
                      if latest_run and latest_run.conclusion == "success":
                          print(f"Found successful test run for {repo_name}")
                          
                          # Use the runs API to get the logs
                          headers = {
                              'Authorization': f'token {token}',
                              'Accept': 'application/vnd.github.v3+json'
                          }
                          
                          # Get logs URL (which is likely a redirect to a download)
                          logs_url = latest_run.logs_url
                          logs_response = requests.get(logs_url, headers=headers, allow_redirects=True)
                          
                          if logs_response.status_code == 200:
                              # Save logs to temporary file and parse
                              with open('temp_logs.zip', 'wb') as f:
                                  f.write(logs_response.content)
                              
                              # Extract and read logs
                              import zipfile
                              import io
                              
                              log_content = ""
                              with zipfile.ZipFile('temp_logs.zip', 'r') as zip_ref:
                                  # Find and read all text files in the zip
                                  for file_info in zip_ref.infolist():
                                      if not file_info.is_dir():
                                          with zip_ref.open(file_info) as f:
                                              try:
                                                  log_content += f.read().decode('utf-8') + "\n"
                                              except UnicodeDecodeError:
                                                  # Skip binary files
                                                  pass
                              
                              # Clean up temp file
                              os.remove('temp_logs.zip')
                              
                              # Extract runtime from logs
                              runtime_match = re.search(r"Rscript calculate_Temp\.R ran in ([\d.]+) seconds", log_content)
                              if runtime_match:
                                  runtime = float(runtime_match.group(1))
                                  # Only store the runtime value
                                  runtime_data.append(runtime)
                                  print(f"Found runtime: {runtime} seconds")
                              else:
                                  print(f"Could not find runtime information in logs for {repo_name}")
                          else:
                              print(f"Failed to download logs for {repo_name}: HTTP {logs_response.status_code}")
                      else:
                          status = latest_run.conclusion if latest_run else "No runs found"
                          print(f"No successful test runs found for {repo_name}. Status: {status}")
                  except Exception as e:
                      print(f"Error processing {repo_name}: {str(e)}")
          
          except Exception as e:
              print(f"Error accessing organization {org_name}: {str(e)}")
              exit(1)
          
          # Sort data by runtime (fastest to slowest)
          runtime_data.sort()
          
          # Save to JSON file
          with open('performance_data.json', 'w') as f:
              json.dump({"runtimes": runtime_data}, f, indent=2)
          
          # Update README.md
          readme_content = ""
          if os.path.exists('README.md'):
              with open('README.md', 'r') as f:
                  readme_content = f.read()
          
          # Create performance table
          performance_table = "## Performance Results\n\n"
          performance_table += "| Rank | Runtime (seconds) |\n"
          performance_table += "|------|------------------|\n"
          
          for i, runtime in enumerate(runtime_data, 1):
              performance_table += f"| {i} | {runtime:.4f} |\n"
          
          # Check if README already has a performance section
          if "## Performance Results" in readme_content:
              # Replace existing section
              readme_content = re.sub(
                  r"## Performance Results\n\n[\s\S]*?(?=\n##|$)",
                  performance_table,
                  readme_content
              )
          else:
              # Append performance section
              readme_content += "\n\n" + performance_table
          
          with open('README.md', 'w') as f:
              f.write(readme_content)
          
          print(f"Processed {len(runtime_data)} successful test runs with runtime data")
          print("Performance data has been saved to performance_data.json and README.md has been updated.")
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add performance_data.json README.md
          git commit -m "Update performance data [skip ci]" || echo "No changes to commit"
          git push 